# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sprodatu <sprodatu@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/04/12 00:15:58 by sprodatu          #+#    #+#              #
#    Updated: 2024/04/13 15:13:32 by sprodatu         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = push_swap
CC = cc
CFLAGS = -Wall -Wextra -Werror -g
LIBFTDIR = libft/
SRCDIR = srcs/
OBJDIR = objs/
BONUS = checker
SRC_1 = srcs/push_swap/push_swap.c
SRC_2 =	srcs/push_swap/algo.c \
		srcs/push_swap/ft_add_back.c \
		srcs/push_swap/ft_check_arguments.c \
		srcs/push_swap/ft_check_dups.c \
		srcs/push_swap/ft_check_sorted.c \
		srcs/push_swap/ft_check_utils.c \
		srcs/push_swap/ft_error_printing.c \
		srcs/push_swap/ft_free.c \
		srcs/push_swap/ft_list_args.c \
		srcs/push_swap/ft_parse_args_quoted.c \
		srcs/push_swap/ft_parse.c \
		srcs/push_swap/ft_rotate_and_push.c \
		srcs/push_swap/ft_rotate_type.c \
		srcs/push_swap/ft_sort_big.c \
		srcs/push_swap/ft_sort_three.c \
		srcs/push_swap/ft_stack_new.c \
		srcs/push_swap/lst_utils.c \
		srcs/push_swap/lst_utils2.c \
		srcs/push_swap/operations.c \
		srcs/push_swap/operations2.c \
		srcs/push_swap/operations3.c \
		srcs/push_swap/solverutilsab.c \
		srcs/push_swap/solverutilsba.c \

BONUS_SRCS =	srcs/checker/checker.c \
				srcs/checker/checker_utils.c \
				srcs/checker/get_next_line.c \
				srcs/checker/get_next_line_utils.c \

INCLUDE = -L ./libft -lft 

OBJ_1 = $(SRC_1:.c=.o)
OBJ_2 = $(SRC_2:.c=.o)
BONUS_OBJS = $(SRC_2:.c=.o) $(BONUS_SRCS:.c=.o)

.c.o:
	$(CC) $(FLAGS) -c $< -o $(<:.c=.o)

$(NAME): $(OBJ_1) $(OBJ_2)
	@make -C $(LIBFTDIR)
	@$(CC) $(FLAGS) $(OBJ_1) $(OBJ_2) -o $(NAME) $(INCLUDE)

bonus: $(BONUS_OBJS) $(OBJ_2)
	@make -C $(LIBFTDIR)
	@$(CC) $(FLAGS) $(BONUS_SRCS:.c=.o) $(OBJ_2) -o $(BONUS) $(INCLUDE)

all: $(NAME)

clean:
	${RM} ${OBJ_1} ${OBJ_2} ${BONUS_OBJS}
	@cd $(LIBFTDIR) && make clean

fclean: clean
	${RM} ${NAME}
	${RM} ${BONUS}
	@cd $(LIBFTDIR) && make fclean

re: fclean all

.PHONY: all clean fclean re
